config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :home, only: [:index] do
    collection do
      post 'subscribe'
    end
  end

  resources :episodes, only: [:show]
  resources :casts, only: [:show]

  namespace :panel do
    root to: 'dashboard#index'

    resources :profile, only: [:edit, :update]

    resources :episodes
    resources :users
    resources :web_shows
    resources :casts
    resources :subscribers, only: [:index, :show] do
      collection do
        get :export
      end
    end
  end

  namespace :api do
    resources :episodes, only: [:index, :show] do
      collection do
        get 'last_episode'
      end
    end
    resources :subscribers, only: [:create]
    resources :casts, only: [:index]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "application"
  respond_to :js, :only => :subscribe, :layout => 'false'

  def index
    @web_show = WebShow.first rescue nil
    @episodes = Episode.where(kind: 1).reorder(created_at: :desc) rescue nil
    @last_episode = Episode.last rescue nil
    @cast = Cast.all rescue nil
  end

  def subscribe
    @subscriber = Subscriber.new
    @subscriber.phone = params[:phone]
    @success = @subscriber.save
    respond_to do |format|
      format.js
    end
  end

end

app/views/home/index.haml
%section#last-episode
  .row.the-last-chapter
    .small-12.medium-12.columns
      = image_tag(@last_episode.picture, class: "floating-image hide-for-small-only") rescue nil
      .row.align-left
        .medium-7.medium-offset-1.small-12.columns
          .chapter-preview
            = image_tag(@last_episode.picture, class: "show-for-small-only") rescue nil
            %span
              = "Capítulo de estreno | #{@last_episode.length} min"
            %h3= @last_episode.title
            %p.summary-text Sinopsis
            %p.summary
              = @last_episode.content

            = link_to image_tag("site/call-to-action-header.png", title: "Reproducir capitulo serie web Los Vecinos"), episode_url(@last_episode), class: "view-last-chapter"
      .row.align-middle
        .small-12.columns
          = link_to "#all-episodes", class: "all-chapters-link" do
            = "Ver capítulos anteriores"
            %br
            = image_tag("site/down.png")
.clearfix
%section#synopsis
  .row.medium-collapse
    .small-12.medium-12.columns.no-padding
      .summary
        %h2 Sinopsis
        = @web_show.try(:synopsis).html_safe
        %br
        = link_to image_tag("site/all-cap.png", title: "Todos los episodios de Los Vecinos"), "#all-episodes", class: "all-chapters-link"
    .small-12.medium-12.columns.no-padding.hide-for-small-only
      .image-wrapper
        = image_tag(@web_show.poster.url, title: "Sinopsis de serie web Los Vecinos", class: "img-synopsis") rescue image_tag("site/foto-sinopsis.png", title: "Sinopsis de serie web Los Vecinos", class: "img-synopsis")
%section#all-episodes
  .row.chapters-wrapper
    .medium-11.medium-offset-1.small-12.columns
      .chapters
        %h2= "Listado de capítulos"
        .premiere
          = "Cada semana se estrenan nuevos capítulos. Si quieres que te notifiquemos, "
          %span
            = "#{link_to('haz click acá','#subscribe')}".html_safe
        - if @episodes.size > 0
          - @episodes.each_with_index do |episode, i|
            .row.chapter
              .small-12.medium-4.columns
                = image_tag(episode.picture.url, class: "last-chapter-img")
              .small-12.medium-7.medium-offset-1.columns
                .chapter-title
                  %h4= episode.title
                  %span= "Cap #{episode.number? ? episode.number.to_s : '-'} | #{episode.length.to_s} min"
                .summary-text.hide-for-small-only Sinopsis
                .summary.hide-for-small-only
                  = episode.content
                .chapter-play-opt
                  = link_to episode_url(episode), class: "play-chapter" do
                    = image_tag("site/play-red.png")
                    %span= "Reproducir capítulo"
                  %p.hide-for-small-only=" | "
                  %div{class: "share-chapter", id: "share-chapter-#{episode.id}"}
                    = image_tag("site/share.png")
                    %span= "Compartir"

%section#subscribe
  .row.let-you-know
    .medium-5.columns.hide-for-small-only
    .medium-7.columns
      %h2 ¡Te avisamos del próximo estreno!
      %p Te notificaremos vía Whatsapp
      = form_tag subscribe_home_index_url, {class: "subscribe-form", id: "subscribe-now", method: :post,  multipart: true, remote: true, authenticity_token: true} do
        .form-wrapper
          .message.callout
            = "¡Te has suscrito exitosamente!"
          .input-group
            %span.input-group-label
              = image_tag("site/wht-icon-color.png")
            = text_field_tag "phone", "", {placeholder: "(51)(4)9999999", class: "input-group-field"}
            .input-group-button
              %input.button{:type => "submit", :value => "Suscribirse", class: "alert"}/


- if @cast.size > 0
  %section#main-cast
    .row
      .medium-12.columns
        %h2 Elenco principal
        %p Conoce un poco más a los vecinos

        .cast-wrapper
          - @cast.each_with_index do |cast, i|
            .cast
              = link_to image_tag(cast.picture.url), cast_url(cast), class: "cast-picture"
              %h3
                = link_to cast_url(cast) do
                  = cast.name
              %p
                = truncate(cast.description, length: 140, omission: '...')

app/views/home/subscribe.js.erb
<%if @success %>
  $(".message").show();
<% else %>
  $(".message").html("<div class='alert'>Ha ocurrido un error.</div>");
<% end %>